

  kong-database:
    image: postgres:15
    container_name: kong_postgres
    restart: always
    environment:
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: kongapass
      POSTGRES_DB: konga
      POSTGRES_INITDB_ARGS: "--auth=md5"
    volumes:
      - /Users/Shared/kongadata/konga-db:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  kong-migrations:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    expose:
      - 5432


  kong:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong_gateway
    restart: always
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://127.0.0.1:8002  
  
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://konga@konga-database:5432/postgres"
    restart: always
    links:
      - kong-database
    depends_on:
      - kong-database
    expose:
      - 5432


  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    depends_on:
      - konga-database
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_PORT: 5432
      DB_USER: konga
      DB_PASSWORD: kongapass
      DB_DATABASE: konga
    volumes:
      - /Users/Shared/kongadata/db:/var/lib/postgresql/data
      - /Users/Shared/kongadata/konga:/app/konga-data 
    ports:
      - "1337:1337"