version: '3.8'

services:
  kong-database:
    image: postgres:15
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: abcd
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: kong
      POSTGRES_INITDB_ARGS: --auth=md5
    volumes:
      - ./kong/postgres:/var/lib/postgresql/data
    expose:
      - 5432
  kong-migrations:
    image: kong:3.5.0
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: abcd
      KONG_PG_PASSWORD: abcd
    expose:
      - 5432
  kong:
    image: kong:3.5.0
    container_name: kong
    restart: always
    depends_on:
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: abcd
      KONG_PG_PASSWORD: abcd
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    
  konga-database:
    image: postgres:11
    container_name: konga-database
    restart: always
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: konga
    volumes:
      - ./konga/postgres:/var/lib/postgresql/data
    expose:
      - 5432

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    depends_on:
      - konga-database
    environment:
      DB_ADAPTER: kong
      DB_HOST: konga-database
      DB_PORT: 5432
      DB_USER: abc
      DB_PASSWORD: abc
      DB_DATABASE: konga
    volumes:
      - ./konga/postgres/data:/var/lib/postgresql/data
      - ./konga/app/konga-data:/app/konga-data 
    ports:
      - "1337:1337"

      